//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/Prefabs/BAV_Prefab/Controller/BAV_PlayerController.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @BAV_PlayerController : IInputActionCollection, IDisposable
{
    public InputActionAsset asset { get; }
    public @BAV_PlayerController()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""BAV_PlayerController"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""2289b125-7141-4017-a061-6c6505b586c4"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""dfa4b4fe-95c9-4a12-8566-ab11730b7f90"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""StickDeadzone"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""26fd18b4-82af-40a1-9773-f7793181f4c3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""XButton"",
                    ""type"": ""Value"",
                    ""id"": ""72633990-087c-4c5c-9117-e9a44f392cbb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""YButton"",
                    ""type"": ""Button"",
                    ""id"": ""58ca634e-3f56-456f-a8b3-da0320a8f40c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AButton"",
                    ""type"": ""Button"",
                    ""id"": ""9821e560-b080-4584-8264-ce58fc5bf2a4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BButton"",
                    ""type"": ""Button"",
                    ""id"": ""4d538565-6a14-419f-905f-decf7717c67f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""56947256-5838-4b17-a2bd-d16c82118be4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left_Top_Trigger"",
                    ""type"": ""Button"",
                    ""id"": ""43040b97-782b-4436-88b0-18e185e4a340"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left_Bottom_Trigger"",
                    ""type"": ""Button"",
                    ""id"": ""f979e8c2-b712-4c1b-96b0-a967f205247f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right_Top_Trigger"",
                    ""type"": ""Button"",
                    ""id"": ""bbafb034-bb52-4c6c-ba0d-9d78c4059419"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right_Bottom_Trigger"",
                    ""type"": ""Button"",
                    ""id"": ""a108a7c0-857d-4e8f-8f60-373596350010"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left_Stick_Press"",
                    ""type"": ""Button"",
                    ""id"": ""9a33f2d1-e242-4996-912c-151150ceeaf3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right_Stick_Press"",
                    ""type"": ""Button"",
                    ""id"": ""cc363f83-64ca-4311-9a1b-8f43b905e88c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""43fc503a-c3d4-4b05-ad63-d19844cf57c2"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": ""Gamepad;Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""ZQSD"",
                    ""id"": ""9ca15c14-e53d-4df8-88cd-ebfde59cde90"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""038d694a-46e4-4c46-850c-c82911603e2e"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""4c3af298-28ac-4e14-998b-afc5e1821506"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f5a7eaa2-aa84-4389-b7fb-be637b714f39"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""42773d34-2c9b-441d-8c57-aeebedf0cf85"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Taiko"",
                    ""id"": ""c5c00ae2-829e-46f3-a828-260765ef2c63"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""4cffc32f-f4ac-4ea8-8454-b4dc4aa27445"",
                    ""path"": ""<HID::HORI CO.,LTD. Taiko Controller>/button12"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""New control scheme"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""4654229f-b204-4501-8295-333f86a183d9"",
                    ""path"": ""<HID::HORI CO.,LTD. Taiko Controller>/button11"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""New control scheme"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""9201ed0c-84e7-4fdb-96b3-2a16ac1a7e1a"",
                    ""path"": ""<HID::HORI CO.,LTD. Taiko Controller>/button7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""New control scheme"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""a66afabd-ccba-4ab0-9a1f-38ac480a89de"",
                    ""path"": ""<HID::HORI CO.,LTD. Taiko Controller>/button8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""New control scheme"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""291f2e59-def6-406f-8c4d-2cf12a4ee06e"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""XButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""60839f66-d277-4d60-bbe1-ad1a7d3f489f"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""XButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1cc37861-0185-495e-a066-4a5dd7b7f44b"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""YButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b24f55aa-91ff-41ec-a0a2-30ff97f2fc69"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""YButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""653b0900-cc12-4cea-b130-31893de91101"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""AButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d47a6c53-6132-4c71-b1fe-d455b2a48f72"",
                    ""path"": ""<HID::HORI CO.,LTD. Taiko Controller>/button4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""New control scheme"",
                    ""action"": ""AButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b5fe4139-504c-42d0-98c5-fb3d45b74d1f"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""AButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f4ec3eba-cf8b-4d82-929e-0b30bcc792b5"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""BButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""202319ea-14b5-4377-9585-80a802713a40"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b730a9e2-027d-4209-8187-493cb3b2bc06"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2213a490-ff42-46c4-80be-b346f38a476a"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""81987cff-8700-4185-a73e-a6c4a49fa4b1"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Left_Bottom_Trigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d28e37ac-5021-4755-b6bf-def163d4b39a"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Right_Bottom_Trigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""726c3b38-d536-4df3-8f8a-fa134ada6c8d"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Right_Top_Trigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00499730-e44d-4c0a-a9cf-7f25e2edf054"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Left_Top_Trigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""62870cb6-88a8-43c9-954a-1cd7ab66383e"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Left_Stick_Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2902b950-65af-4d3e-bca7-7ce0245881ee"",
                    ""path"": ""<XInputController>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left_Stick_Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""792d45e9-0193-489c-b15e-4fb20f9ef410"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Right_Stick_Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3273b646-00ac-4f03-a334-237f9c83bc7d"",
                    ""path"": ""<XInputController>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Right_Stick_Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""fcfb97a4-a647-49ec-99f8-b10061d2d5bd"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""PassThrough"",
                    ""id"": ""836a28a0-ab9a-43f2-bb9c-06c686f3170e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Selected"",
                    ""type"": ""PassThrough"",
                    ""id"": ""2b80f2a1-4912-44f9-a18c-8a1e2240d250"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PauseGame"",
                    ""type"": ""PassThrough"",
                    ""id"": ""5b4492b5-fe60-40ff-bbac-e0637f0daeda"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""cb0626cd-49a3-4a53-a7c9-6bf8cd5bd197"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Selected"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""D PAD"",
                    ""id"": ""3ef257dc-a370-4f14-bad1-9f6e8f7b7c68"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""5700b130-f10b-4d6b-b01f-da558e5fe1d8"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""31423c1d-b994-448a-a1f1-430fc42ea97a"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""521790a6-429d-4ee4-8b23-c27f0ce51212"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""8d383c28-6aa4-4430-9851-167efff56cee"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Taiko"",
                    ""id"": ""7ee1115f-ac20-4d85-b3f4-51c4180b8e3a"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""New control scheme"",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""09e3afab-f1e7-4d83-bfe3-1cda67166945"",
                    ""path"": ""<HID::HORI CO.,LTD. Taiko Controller>/button12"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""New control scheme"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b0b4523a-be0d-4aec-846b-8567b8d07688"",
                    ""path"": ""<HID::HORI CO.,LTD. Taiko Controller>/button11"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""New control scheme"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""c6a49ad1-3950-4663-beeb-aa566d6819d1"",
                    ""path"": ""<HID::HORI CO.,LTD. Taiko Controller>/button7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""New control scheme"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""7f0f5971-199c-47c9-82aa-e7bc098d29db"",
                    ""path"": ""<HID::HORI CO.,LTD. Taiko Controller>/button8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""New control scheme"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""fcc2fd5e-e630-44ab-803a-ce2ec89f9a38"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f91b3229-baf8-44d7-a49b-54da8884ac92"",
                    ""path"": ""<HID::HORI CO.,LTD. Taiko Controller>/button4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""New control scheme"",
                    ""action"": ""Selected"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c214a9f5-15ea-4ddc-a2a7-f0bf6f73b3e5"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PauseGame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""New control scheme"",
            ""bindingGroup"": ""New control scheme"",
            ""devices"": [
                {
                    ""devicePath"": ""<HID::HORI CO.,LTD. Taiko Controller>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
        m_Player_Look = m_Player.FindAction("Look", throwIfNotFound: true);
        m_Player_XButton = m_Player.FindAction("XButton", throwIfNotFound: true);
        m_Player_YButton = m_Player.FindAction("YButton", throwIfNotFound: true);
        m_Player_AButton = m_Player.FindAction("AButton", throwIfNotFound: true);
        m_Player_BButton = m_Player.FindAction("BButton", throwIfNotFound: true);
        m_Player_Select = m_Player.FindAction("Select", throwIfNotFound: true);
        m_Player_Left_Top_Trigger = m_Player.FindAction("Left_Top_Trigger", throwIfNotFound: true);
        m_Player_Left_Bottom_Trigger = m_Player.FindAction("Left_Bottom_Trigger", throwIfNotFound: true);
        m_Player_Right_Top_Trigger = m_Player.FindAction("Right_Top_Trigger", throwIfNotFound: true);
        m_Player_Right_Bottom_Trigger = m_Player.FindAction("Right_Bottom_Trigger", throwIfNotFound: true);
        m_Player_Left_Stick_Press = m_Player.FindAction("Left_Stick_Press", throwIfNotFound: true);
        m_Player_Right_Stick_Press = m_Player.FindAction("Right_Stick_Press", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_Move = m_UI.FindAction("Move", throwIfNotFound: true);
        m_UI_Selected = m_UI.FindAction("Selected", throwIfNotFound: true);
        m_UI_PauseGame = m_UI.FindAction("PauseGame", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Move;
    private readonly InputAction m_Player_Look;
    private readonly InputAction m_Player_XButton;
    private readonly InputAction m_Player_YButton;
    private readonly InputAction m_Player_AButton;
    private readonly InputAction m_Player_BButton;
    private readonly InputAction m_Player_Select;
    private readonly InputAction m_Player_Left_Top_Trigger;
    private readonly InputAction m_Player_Left_Bottom_Trigger;
    private readonly InputAction m_Player_Right_Top_Trigger;
    private readonly InputAction m_Player_Right_Bottom_Trigger;
    private readonly InputAction m_Player_Left_Stick_Press;
    private readonly InputAction m_Player_Right_Stick_Press;
    public struct PlayerActions
    {
        private @BAV_PlayerController m_Wrapper;
        public PlayerActions(@BAV_PlayerController wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Player_Move;
        public InputAction @Look => m_Wrapper.m_Player_Look;
        public InputAction @XButton => m_Wrapper.m_Player_XButton;
        public InputAction @YButton => m_Wrapper.m_Player_YButton;
        public InputAction @AButton => m_Wrapper.m_Player_AButton;
        public InputAction @BButton => m_Wrapper.m_Player_BButton;
        public InputAction @Select => m_Wrapper.m_Player_Select;
        public InputAction @Left_Top_Trigger => m_Wrapper.m_Player_Left_Top_Trigger;
        public InputAction @Left_Bottom_Trigger => m_Wrapper.m_Player_Left_Bottom_Trigger;
        public InputAction @Right_Top_Trigger => m_Wrapper.m_Player_Right_Top_Trigger;
        public InputAction @Right_Bottom_Trigger => m_Wrapper.m_Player_Right_Bottom_Trigger;
        public InputAction @Left_Stick_Press => m_Wrapper.m_Player_Left_Stick_Press;
        public InputAction @Right_Stick_Press => m_Wrapper.m_Player_Right_Stick_Press;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Look.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                @Look.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                @Look.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                @XButton.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnXButton;
                @XButton.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnXButton;
                @XButton.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnXButton;
                @YButton.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnYButton;
                @YButton.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnYButton;
                @YButton.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnYButton;
                @AButton.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAButton;
                @AButton.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAButton;
                @AButton.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAButton;
                @BButton.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBButton;
                @BButton.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBButton;
                @BButton.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBButton;
                @Select.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelect;
                @Select.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelect;
                @Select.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelect;
                @Left_Top_Trigger.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeft_Top_Trigger;
                @Left_Top_Trigger.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeft_Top_Trigger;
                @Left_Top_Trigger.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeft_Top_Trigger;
                @Left_Bottom_Trigger.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeft_Bottom_Trigger;
                @Left_Bottom_Trigger.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeft_Bottom_Trigger;
                @Left_Bottom_Trigger.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeft_Bottom_Trigger;
                @Right_Top_Trigger.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRight_Top_Trigger;
                @Right_Top_Trigger.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRight_Top_Trigger;
                @Right_Top_Trigger.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRight_Top_Trigger;
                @Right_Bottom_Trigger.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRight_Bottom_Trigger;
                @Right_Bottom_Trigger.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRight_Bottom_Trigger;
                @Right_Bottom_Trigger.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRight_Bottom_Trigger;
                @Left_Stick_Press.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeft_Stick_Press;
                @Left_Stick_Press.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeft_Stick_Press;
                @Left_Stick_Press.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeft_Stick_Press;
                @Right_Stick_Press.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRight_Stick_Press;
                @Right_Stick_Press.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRight_Stick_Press;
                @Right_Stick_Press.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRight_Stick_Press;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
                @XButton.started += instance.OnXButton;
                @XButton.performed += instance.OnXButton;
                @XButton.canceled += instance.OnXButton;
                @YButton.started += instance.OnYButton;
                @YButton.performed += instance.OnYButton;
                @YButton.canceled += instance.OnYButton;
                @AButton.started += instance.OnAButton;
                @AButton.performed += instance.OnAButton;
                @AButton.canceled += instance.OnAButton;
                @BButton.started += instance.OnBButton;
                @BButton.performed += instance.OnBButton;
                @BButton.canceled += instance.OnBButton;
                @Select.started += instance.OnSelect;
                @Select.performed += instance.OnSelect;
                @Select.canceled += instance.OnSelect;
                @Left_Top_Trigger.started += instance.OnLeft_Top_Trigger;
                @Left_Top_Trigger.performed += instance.OnLeft_Top_Trigger;
                @Left_Top_Trigger.canceled += instance.OnLeft_Top_Trigger;
                @Left_Bottom_Trigger.started += instance.OnLeft_Bottom_Trigger;
                @Left_Bottom_Trigger.performed += instance.OnLeft_Bottom_Trigger;
                @Left_Bottom_Trigger.canceled += instance.OnLeft_Bottom_Trigger;
                @Right_Top_Trigger.started += instance.OnRight_Top_Trigger;
                @Right_Top_Trigger.performed += instance.OnRight_Top_Trigger;
                @Right_Top_Trigger.canceled += instance.OnRight_Top_Trigger;
                @Right_Bottom_Trigger.started += instance.OnRight_Bottom_Trigger;
                @Right_Bottom_Trigger.performed += instance.OnRight_Bottom_Trigger;
                @Right_Bottom_Trigger.canceled += instance.OnRight_Bottom_Trigger;
                @Left_Stick_Press.started += instance.OnLeft_Stick_Press;
                @Left_Stick_Press.performed += instance.OnLeft_Stick_Press;
                @Left_Stick_Press.canceled += instance.OnLeft_Stick_Press;
                @Right_Stick_Press.started += instance.OnRight_Stick_Press;
                @Right_Stick_Press.performed += instance.OnRight_Stick_Press;
                @Right_Stick_Press.canceled += instance.OnRight_Stick_Press;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private IUIActions m_UIActionsCallbackInterface;
    private readonly InputAction m_UI_Move;
    private readonly InputAction m_UI_Selected;
    private readonly InputAction m_UI_PauseGame;
    public struct UIActions
    {
        private @BAV_PlayerController m_Wrapper;
        public UIActions(@BAV_PlayerController wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_UI_Move;
        public InputAction @Selected => m_Wrapper.m_UI_Selected;
        public InputAction @PauseGame => m_Wrapper.m_UI_PauseGame;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void SetCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_UIActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnMove;
                @Selected.started -= m_Wrapper.m_UIActionsCallbackInterface.OnSelected;
                @Selected.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnSelected;
                @Selected.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnSelected;
                @PauseGame.started -= m_Wrapper.m_UIActionsCallbackInterface.OnPauseGame;
                @PauseGame.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnPauseGame;
                @PauseGame.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnPauseGame;
            }
            m_Wrapper.m_UIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Selected.started += instance.OnSelected;
                @Selected.performed += instance.OnSelected;
                @Selected.canceled += instance.OnSelected;
                @PauseGame.started += instance.OnPauseGame;
                @PauseGame.performed += instance.OnPauseGame;
                @PauseGame.canceled += instance.OnPauseGame;
            }
        }
    }
    public UIActions @UI => new UIActions(this);
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    private int m_NewcontrolschemeSchemeIndex = -1;
    public InputControlScheme NewcontrolschemeScheme
    {
        get
        {
            if (m_NewcontrolschemeSchemeIndex == -1) m_NewcontrolschemeSchemeIndex = asset.FindControlSchemeIndex("New control scheme");
            return asset.controlSchemes[m_NewcontrolschemeSchemeIndex];
        }
    }
    public interface IPlayerActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnXButton(InputAction.CallbackContext context);
        void OnYButton(InputAction.CallbackContext context);
        void OnAButton(InputAction.CallbackContext context);
        void OnBButton(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
        void OnLeft_Top_Trigger(InputAction.CallbackContext context);
        void OnLeft_Bottom_Trigger(InputAction.CallbackContext context);
        void OnRight_Top_Trigger(InputAction.CallbackContext context);
        void OnRight_Bottom_Trigger(InputAction.CallbackContext context);
        void OnLeft_Stick_Press(InputAction.CallbackContext context);
        void OnRight_Stick_Press(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnSelected(InputAction.CallbackContext context);
        void OnPauseGame(InputAction.CallbackContext context);
    }
}
